import VPlay 1.0

Particles {
    finishColorVarianceBlue: 0
    rotatePerSecondVariance: 0
    finishColorBlue: 0.300000011920929
    blendFuncDestination: 771
    startParticleSize: 15
    finishParticleSize: 50
    radialAccelVariance: 0
    gravityy: 0
    sourcePositionVariancey: 0
    rotatePerSecond: 0
    startColorBlue: 0.75
    textureFileName: "particleBlood.png"
    finishParticleSizeVariance: 0
    startColorVarianceBlue: 0
    duration: 2
    emitterType: 0
    maxRadiusVariance: 0
    rotationStartVariance: 0
    speedVariance: 0
    startColorGreen: 0.75
    blendFuncSource: 770
    rotationStart: 0
    minRadius: 0
    sourcePositionx: 0
    finishColorAlpha: 0
    startColorRed: 1
    angleVariance: 360
    finishColorVarianceGreen: 0
    startColorVarianceRed: 0
    tangentialAcceleration: 0
    finishColorGreen: 0.300000011920929
    rotationEnd: 0
    maxRadius: 100
    gravityx: 0
    finishColorVarianceRed: 0
    startColorVarianceAlpha: 0
    finishColorRed: 0.300000011920929
    particleLifespan: 3
    sourcePositionVariancex: 0
    finishColorVarianceAlpha: 0
    startColorVarianceGreen: 0
    tangentialAccelVariance: 0
    maxParticles: 10
    particleLifespanVariance: 0
    radialAcceleration: 0
    rotationEndVariance: 0
    sourcePositiony: 0
    angle: 90
    startColorAlpha: 0.800000011920929
    startParticleSizeVariance: 0
    speed: 0
}
