import VPlay 1.0

Particles {
    finishColorVarianceBlue: 0
    rotatePerSecondVariance: 0
    finishColorBlue: 0
    blendFuncDestination: 1
    startParticleSize: 7
    finishParticleSize: 45
    radialAccelVariance: 0
    gravityy: 0
    sourcePositionVariancey: 0
    rotatePerSecond: 0
    startColorBlue: 0.119999997317791
    textureFileName: "particleFire.png"
    finishParticleSizeVariance: 10
    startColorVarianceBlue: 0
    duration: -1
    emitterType: 0
    maxRadiusVariance: 0
    rotationStartVariance: 0
    speedVariance: 2
    startColorGreen: 0.25
    blendFuncSource: 770
    rotationStart: 0
    minRadius: 0
    sourcePositionx: 15
    finishColorAlpha: 1
    startColorRed: 0.7599999904632568
    angleVariance: 0
    finishColorVarianceGreen: 0
    startColorVarianceRed: 0
    tangentialAcceleration: 0
    finishColorGreen: 0
    rotationEnd: 0
    maxRadius: 100
    gravityx: 0
    finishColorVarianceRed: 0
    startColorVarianceAlpha: 0
    finishColorRed: 0
    particleLifespan: 0.8999999761581421
    sourcePositionVariancex: 0
    finishColorVarianceAlpha: 0
    startColorVarianceGreen: 0
    tangentialAccelVariance: 0
    maxParticles: 50
    particleLifespanVariance: 0.2000000029802322
    radialAcceleration: 0
    rotationEndVariance: 0
    sourcePositiony: 0
    angle: 0
    startColorAlpha: 1
    startParticleSizeVariance: 2
    speed: 85
}
