import VPlay 1.0

Particles {
    finishColorVarianceBlue: 0
    rotatePerSecondVariance: 0
    finishColorBlue: 0.1000000014901161
    blendFuncDestination: 771
    startParticleSize: 7
    finishParticleSize: 30
    radialAccelVariance: 10
    gravityy: 30
    sourcePositionVariancey: 5
    rotatePerSecond: 0
    startColorBlue: 0.75
    textureFileName: "particleSmoke.png"
    finishParticleSizeVariance: 10
    startColorVarianceBlue: 0
    duration: 5
    emitterType: 0
    maxRadiusVariance: 0
    rotationStartVariance: 0
    speedVariance: 0
    startColorGreen: 0.75
    blendFuncSource: 770
    rotationStart: 0
    minRadius: 0
    sourcePositionx: 0
    finishColorAlpha: 0
    startColorRed: 0.75
    angleVariance: 60
    finishColorVarianceGreen: 0
    startColorVarianceRed: 0
    tangentialAcceleration: 0
    finishColorGreen: 0.1000000014901161
    rotationEnd: 0
    maxRadius: 100
    gravityx: 0
    finishColorVarianceRed: 0
    startColorVarianceAlpha: 0
    finishColorRed: 0.1000000014901161
    particleLifespan: 2
    sourcePositionVariancex: 5
    finishColorVarianceAlpha: 0
    startColorVarianceGreen: 0
    tangentialAccelVariance: 0
    maxParticles: 20
    particleLifespanVariance: 1
    radialAcceleration: -30
    rotationEndVariance: 0
    sourcePositiony: 0
    angle: 90
    startColorAlpha: 0.800000011920929
    startParticleSizeVariance: 3
    speed: 10
}
